### ISSUE TITLE
values spawning 

### ISSUE THREAD

**Issue by maximburdiean** [Alexpol19/AdminUi#7]
Много мест, где можно сразу вернуть результат, без создания переменных:
![image](https://user-images.githubusercontent.com/5040836/98916594-0629c700-24d4-11eb-9899-31375dcdd49c.png)

**Comment by Alexpol19** [comment]
Согласен. Мало уделил времени рефакторингу. Привык для себя подробнее писать + Мало опыта. Но можно короче.

**Comment by maximburdiean** [comment]
закрываю
